#!/usr/bin/env bash
# Render every kustomize overlay under kustomize/overlays/ and fail loudly if any
# genuinely fails to build. This is the cross-overlay counterpart to the one-off
# `kubectl kustomize kustomize/overlays/<one>` checks that were previously the only
# verification this repo had — for an infra repo with no unit-test suite, "every
# overlay still renders" IS the test.
#
# Usage: tests/render-all.sh
# Env:   KUSTOMIZE_BIN — path to a kustomize binary to prefer (see renderer
#        selection below).
#
# Overlays are discovered dynamically (never hardcoded): ad-hoc instance overlays
# generated by scripts/start-server.sh are gitignored and come and go, so a fixed
# list would silently stop covering them.
#
# Every overlay is ALWAYS built (build-first, reclassify-second) — never skipped
# up front on a static guess. Only a build that actually FAILS is inspected, and
# only reclassified to SKIP if kustomize's own error names the missing gitignored
# secret.yaml. Any other failure — a bad patch, a YAML mistake, a dangling
# resource reference — is a genuine FAIL with the real error printed. A static
# pre-check would let exactly that kind of mistake through silently, and since
# scripts/start-server.sh gives every generated instance overlay a secret.yaml
# entry in `resources:`, generated overlays (the ones most likely to contain a
# mistake) are exactly the ones a static check would blind itself to.
#
# A missing secret.yaml fails during kustomize's resource ACCUMULATION step, before
# patches or manifests are even considered — so an overlay with both a missing
# secret AND a broken patch would still build-fail on the missing secret and never
# reach the real bug. To tell those apart, a missing-secret failure gets a second
# build attempt with a temporary dummy secret.yaml in place: if that build
# succeeds, it really was only the missing secret (SKIP); if it still fails, the
# overlay is broken for a real reason (FAIL), and that second error is printed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OVERLAYS_DIR="$ROOT/kustomize/overlays"

# True if $2 (a kustomize stderr capture) indicates $1 (an overlay dir) failed
# to build because its gitignored secret.yaml is missing — the ONE reason a
# build failure gets reclassified as SKIP instead of FAIL below, and the ONE
# reason the renderer-capability probe below treats a failure as inconclusive
# instead of blaming the renderer. Checked two ways on purpose: the file must
# be genuinely absent AND the error text must name it, so an unrelated error
# that happens to mention "secret.yaml" is never misread as this case.
is_missing_secret_failure() {
  local dir="$1" err="$2"
  [[ ! -f "${dir}secret.yaml" ]] && grep -qE 'secret\.yaml.*no such file or directory' <<<"$err"
}

shopt -s nullglob
overlay_dirs=("$OVERLAYS_DIR"/*/)
shopt -u nullglob

if (( ${#overlay_dirs[@]} == 0 )); then
  echo "ERROR: no overlays found under $OVERLAYS_DIR" >&2
  exit 2
fi

# --- Renderer selection ------------------------------------------------------
# Pick the renderer by CAPABILITY, not by name. Hardcoding `kubectl kustomize`
# pins this script to whatever kustomize happens to be vendored inside
# whatever `kubectl` is on PATH — on a machine with an old kubectl that can be
# kustomize < 3.7, which chokes on `components:` with a "json: unknown field"
# error that reads like a manifest bug and sends you hunting through YAML that
# is perfectly fine. `components:` needs kustomize >= 3.7 and `labels:` needs
# >= 4.x, so any repo using modern Kustomize idioms hits this on a stale box.
#
# KUSTOMIZE_BIN is tried first so a machine whose system tooling is too old to
# upgrade cheaply can point at a binary it unpacked somewhere else, then a
# standalone `kustomize` on PATH, then `kubectl kustomize` as the fallback.
#
# Deliberately NOT parsing `kustomize version` output: the format changed
# across releases (v3 prints a `Version: {Version:3.2.1 ...}` struct, v5
# prints a bare `v5.8.1`), and what matters is whether it renders THIS repo,
# not what it calls itself — so each candidate is probed by actually trying
# to build an overlay.
#
# Capability-probe idea adapted from SiliconSaga/xenforo-k8s, which itself
# adapted this file. Its probe only ever tried the first overlay alphabetically
# — fine there, but this repo's SKIP concept (above) means an overlay can
# legitimately fail to build for a reason that says nothing about renderer
# capability: scripts/start-server.sh gives every generated instance overlay a
# secret.yaml entry, so an alphabetically-early generated overlay with an
# unrendered secret would make every candidate "fail" and wrongly announce
# "your renderer is too old" when the real cause is just an unrendered secret.
# So here, a missing-secret failure is treated as INCONCLUSIVE about capability
# — the probe moves on to the next overlay instead of condemning the renderer
# — and only concludes "no working renderer" once a candidate has failed for a
# real reason, or every overlay has been tried inconclusively.
candidates=()
[[ -n "${KUSTOMIZE_BIN:-}" ]] && candidates+=("$KUSTOMIZE_BIN build")
command -v kustomize >/dev/null 2>&1 && candidates+=("kustomize build")
command -v kubectl   >/dev/null 2>&1 && candidates+=("kubectl kustomize")

if (( ${#candidates[@]} == 0 )); then
  echo "ERROR: need either 'kustomize' or 'kubectl' on PATH (or KUSTOMIZE_BIN set)." >&2
  exit 2
fi

probe_err=""
renderer=""
for overlay_dir in "${overlay_dirs[@]}"; do
  genuine_failure=""
  for candidate in "${candidates[@]}"; do
    if err="$($candidate "$overlay_dir" 2>&1 >/dev/null)"; then
      renderer="$candidate"
      break 2
    fi
    if is_missing_secret_failure "$overlay_dir" "$err"; then
      # Inconclusive for this candidate on this overlay — try the next
      # candidate (or, once all candidates are exhausted, the next overlay)
      # rather than blaming the renderer.
      continue
    fi
    genuine_failure=1
    [[ -z "$probe_err" ]] && probe_err="$err"
  done
  # Every candidate failed on this overlay. If none of those failures were
  # genuine (all were the inconclusive missing-secret case), a later overlay
  # might not need a secret at all — keep looking. A genuine failure means
  # we've learned something real about renderer capability, so stop.
  [[ -n "$genuine_failure" ]] && break
done

if [[ -z "$renderer" ]]; then
  echo "ERROR: no available renderer could build any overlay under $OVERLAYS_DIR" >&2
  echo >&2
  if [[ -n "$probe_err" ]]; then
    sed 's/^/    /' <<<"$probe_err" >&2
  else
    echo "    (every failure was an unrendered secret.yaml — render one with scripts/render-secret.sh <name> and retry)" >&2
  fi
  if grep -qE 'unknown field "(components|labels)"' <<<"$probe_err"; then
    cat >&2 <<'EOF'

Every renderer found is too old for this repo: `components:` needs kustomize >= 3.7
and `labels:` needs >= 4.x. Fix it with one of:

  brew install kustomize                       # or your platform's package manager
  KUSTOMIZE_BIN=/path/to/kustomize tests/render-all.sh

Release binaries: https://github.com/kubernetes-sigs/kustomize/releases
EOF
  fi
  exit 2
fi

echo "Renderer: $renderer"
echo
# --- End renderer selection ---------------------------------------------------

pass=0
skip=0
fail=0

stderr_file="$(mktemp)"
# Tracks a dummy secret.yaml currently on disk, if any, so cleanup can remove it
# even on an early/unexpected exit. A leftover dummy secret in an overlay
# directory would silently satisfy a real deployment with a junk password.
dummy_secret=""
cleanup() {
  rm -f "$stderr_file"
  if [[ -n "$dummy_secret" && -f "$dummy_secret" ]]; then
    rm -f "$dummy_secret"
  fi
}
trap cleanup EXIT

for overlay_dir in "${overlay_dirs[@]}"; do
  name="$(basename "$overlay_dir")"

  if $renderer "$overlay_dir" >/dev/null 2>"$stderr_file"; then
    echo "PASS: $name"
    pass=$((pass + 1))
    continue
  fi

  build_err="$(cat "$stderr_file")"

  # Reclassify to SKIP only if kustomize's own error names a missing secret.yaml
  # AND the file is genuinely absent (not some unrelated error that happens to
  # mention the string). This is the legitimate, expected case of a gitignored
  # secret that hasn't been rendered yet (e.g. a fresh clone) — never a guess.
  if is_missing_secret_failure "$overlay_dir" "$build_err"; then
    dummy_secret="${overlay_dir}secret.yaml"
    cat > "$dummy_secret" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: valheim-secrets
type: Opaque
stringData:
  serverPass: "DUMMY-RENDER-TEST-ONLY"
YAML

    if $renderer "$overlay_dir" >/dev/null 2>"$stderr_file"; then
      echo "SKIP (secret not rendered): $name — run scripts/render-secret.sh $name"
      skip=$((skip + 1))
      rm -f "$dummy_secret"
      dummy_secret=""
      continue
    fi

    # The overlay is broken for reasons beyond the missing secret — genuine FAIL,
    # with the second build's error (the real one) printed instead of the first.
    second_err="$(cat "$stderr_file")"
    rm -f "$dummy_secret"
    dummy_secret=""
    echo "FAIL: $name (missing secret AND a broken build beyond that)"
    sed 's/^/    /' <<<"$second_err"
    fail=$((fail + 1))
    continue
  fi

  echo "FAIL: $name"
  sed 's/^/    /' <<<"$build_err"
  fail=$((fail + 1))
done

echo
echo "Summary: ${pass} passed, ${skip} skipped, ${fail} failed"

if (( fail > 0 )); then
  exit 1
fi
