#!/usr/bin/env bash
# Render every kustomize overlay under kustomize/overlays/ and fail loudly if any
# genuinely fails to build. This is the cross-overlay counterpart to the one-off
# `kubectl kustomize kustomize/overlays/<one>` checks that were previously the only
# verification this repo had — for an infra repo with no unit-test suite, "every
# overlay still renders" IS the test.
#
# Usage: tests/render-all.sh
# Env:   KUSTOMIZE_BIN — path to a kustomize binary to prefer (see renderer
#        selection below).
#
# Overlays are discovered dynamically (never hardcoded): ad-hoc instance overlays
# generated by scripts/create-server.sh are gitignored and come and go, so a fixed
# list would silently stop covering them.
#
# Every overlay is ALWAYS built (build-first, reclassify-second) — never skipped
# up front on a static guess. Only a build that actually FAILS is inspected, and
# only reclassified to SKIP if kustomize's own error names the missing gitignored
# secret.yaml. Any other failure — a bad patch, a YAML mistake, a dangling
# resource reference — is a genuine FAIL with the real error printed. A static
# pre-check would let exactly that kind of mistake through silently, and since
# scripts/create-server.sh gives every generated instance overlay a secret.yaml
# entry in `resources:`, generated overlays (the ones most likely to contain a
# mistake) are exactly the ones a static check would blind itself to.
#
# A missing secret.yaml fails during kustomize's resource ACCUMULATION step, before
# patches or manifests are even considered — so an overlay with both a missing
# secret AND a broken patch would still build-fail on the missing secret and never
# reach the real bug. To tell those apart, a missing-secret failure gets a second
# build attempt with a temporary dummy secret.yaml in place: if that build
# succeeds, it really was only the missing secret (SKIP); if it still fails, the
# overlay is broken for a real reason (FAIL), and that second error is printed.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OVERLAYS_DIR="$ROOT/kustomize/overlays"

# True if $2 (a kustomize stderr capture) indicates $1 (an overlay dir) failed
# to build because its gitignored secret.yaml is missing — the ONE reason a
# build failure gets reclassified as SKIP instead of FAIL below. Checked two
# ways on purpose: the file must be genuinely absent AND the error text must
# name it, so an unrelated error that happens to mention "secret.yaml" is
# never misread as this case.
is_missing_secret_failure() {
  local dir="$1" err="$2"
  [[ ! -f "${dir}secret.yaml" ]] && grep -qE 'secret\.yaml.*no such file or directory' <<<"$err"
}

shopt -s nullglob
overlay_dirs=("$OVERLAYS_DIR"/*/)
shopt -u nullglob

if (( ${#overlay_dirs[@]} == 0 )); then
  echo "ERROR: no overlays found under $OVERLAYS_DIR" >&2
  exit 2
fi

# --- Cleanup plumbing (set up early so it also covers the fixture below) ----
stderr_file="$(mktemp)"
# Tracks a dummy secret.yaml currently on disk, if any, so cleanup can remove it
# even on an early/unexpected exit. A leftover dummy secret in an overlay
# directory would silently satisfy a real deployment with a junk password.
dummy_secret=""
# Tracks the synthetic renderer-capability fixture dir (see below) so cleanup
# removes it too, on any exit path.
fixture_dir=""
cleanup() {
  rm -f "$stderr_file"
  if [[ -n "$dummy_secret" && -f "$dummy_secret" ]]; then
    rm -f "$dummy_secret"
  fi
  if [[ -n "$fixture_dir" && -d "$fixture_dir" ]]; then
    rm -rf "$fixture_dir"
  fi
}
trap cleanup EXIT

# --- Renderer selection ------------------------------------------------------
# Pick the renderer by CAPABILITY, not by name. Hardcoding `kubectl kustomize`
# pins this script to whatever kustomize happens to be vendored inside
# whatever `kubectl` is on PATH — on a machine with an old kubectl that can be
# kustomize < 3.7, which chokes on `components:` with a "json: unknown field"
# error that reads like a manifest bug and sends you hunting through YAML that
# is perfectly fine. `components:` needs kustomize >= 3.7 and `labels:` needs
# >= 4.x, so any repo using modern Kustomize idioms hits this on a stale box.
#
# KUSTOMIZE_BIN is tried first so a machine whose system tooling is too old to
# upgrade cheaply can point at a binary it unpacked somewhere else, then a
# standalone `kustomize` on PATH, then `kubectl kustomize` as the fallback.
#
# Deliberately NOT parsing `kustomize version` output: the format changed
# across releases (v3 prints a `Version: {Version:3.2.1 ...}` struct, v5
# prints a bare `v5.8.1`), and what matters is whether it renders the features
# this repo uses, not what it calls itself — so each candidate is probed by
# actually trying to build something that needs those features.
#
# Probed against a tiny SYNTHETIC fixture built in a temp dir — never against
# a real overlay under kustomize/overlays/. Capability and repo state used to
# be conflated here: an earlier version probed the first repo overlay
# (alphabetically), then every repo overlay in turn skipping "inconclusive"
# missing-secret failures. That still let ONE broken-for-real overlay that
# happened to sort/probe first condemn every candidate renderer with "your
# renderer is too old" — blaming tooling for what was actually one broken
# overlay, and that overlay never got reported as FAIL. Probing a fixture that
# this script fully controls makes the capability question independent of
# repo state: a broken repo overlay now simply reports FAIL like any other
# below, and "your renderer is too old" is only ever printed when it's true of
# the fixture, which exercises exactly the two features that need modern
# kustomize: a `kustomization.yaml` using `components:` and `labels:` (with
# `includeSelectors`).
#
# Capability-probe idea adapted from SiliconSaga/xenforo-k8s, which itself
# adapted this file.
fixture_dir="$(mktemp -d)"
mkdir -p "$fixture_dir/component"

cat > "$fixture_dir/kustomization.yaml" <<'YAML'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
components:
  - component
labels:
  - pairs:
      probe: "true"
    includeSelectors: true
YAML

# A Deployment and a Service, each with their own selector, so includeSelectors
# has two independent places to prove it actually injected the label into —
# not just metadata.labels, which a renderer could honour while still getting
# includeSelectors wrong.
cat > "$fixture_dir/deployment.yaml" <<'YAML'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe
  template:
    metadata:
      labels:
        app: probe
    spec:
      containers:
        - name: probe
          image: busybox:1.36
YAML

cat > "$fixture_dir/service.yaml" <<'YAML'
apiVersion: v1
kind: Service
metadata:
  name: probe
spec:
  selector:
    app: probe
  ports:
    - port: 80
YAML

cat > "$fixture_dir/component/kustomization.yaml" <<'YAML'
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - extra-configmap.yaml
YAML

cat > "$fixture_dir/component/extra-configmap.yaml" <<'YAML'
apiVersion: v1
kind: ConfigMap
metadata:
  name: probe-extra
data:
  key: value
YAML

# Candidates are identified by a plain id string (kustomize_bin / kustomize /
# kubectl), dispatched through `case` — NOT bash arrays-of-arrays via `eval`.
# Bash can't nest arrays, and the previous version worked around that with a
# script-constructed variable name rebuilt into an argv via `eval`. That eval
# was always on a fixed name this script itself built, never on external
# input, so it wasn't unsafe — but it's unneeded complexity a `case` avoids
# entirely, and it's one more thing to reason about when reading this file.
# (Design adapted from SiliconSaga/xenforo-k8s, which itself adapted this
# file.) render_with actually runs a candidate; label_for prints its display
# name. Both switch on the same id, so adding a candidate means editing both
# in lockstep — and the fixed set of ids below.
render_with() {
  # $1 = candidate id, $2 = directory to build.
  case "$1" in
    kustomize_bin) "$KUSTOMIZE_BIN" build "$2" ;;
    kustomize)     kustomize build "$2" ;;
    kubectl)       kubectl kustomize "$2" ;;
  esac
}

label_for() {
  # $1 = candidate id.
  case "$1" in
    kustomize_bin) printf '%s build' "$KUSTOMIZE_BIN" ;;
    kustomize)     printf 'kustomize build' ;;
    kubectl)       printf 'kubectl kustomize' ;;
  esac
}

# A renderer can exit 0 on the fixture while silently ignoring `components:` or
# `includeSelectors` — the exact capability being probed — so exit status alone
# is not proof. This inspects the RENDERED OUTPUT for both:
#   (a) the component's ConfigMap present at all, proving `components:` pulled
#       it in;
#   (b) the injected `probe: "true"` label present in BOTH the Deployment's
#       spec.selector.matchLabels AND the Service's spec.selector, proving
#       `includeSelectors: true` actually rewrote selectors and not just
#       metadata.labels.
# Only a candidate whose output passes both is treated as capable.
assert_capability_output() {
  local out="$1"
  local split_dir
  split_dir="$(mktemp -d)"
  awk -v dir="$split_dir" '
    BEGIN { n = 0; file = dir "/doc0.yaml" }
    /^---[[:space:]]*$/ { n++; file = dir "/doc" n ".yaml"; next }
    { print > file }
  ' <<<"$out"

  local has_configmap=0 deploy_ok=0 svc_ok=0 f
  for f in "$split_dir"/doc*.yaml; do
    [[ -f "$f" ]] || continue
    if grep -q '^kind: ConfigMap$' "$f" && grep -q '^  name: probe-extra$' "$f"; then
      has_configmap=1
    fi
    if grep -q '^kind: Deployment$' "$f"; then
      if awk '/^  selector:/{f=1} /^  template:/{f=0} f' "$f" | grep -q 'probe: "true"'; then
        deploy_ok=1
      fi
    fi
    if grep -q '^kind: Service$' "$f"; then
      if awk '/^  selector:/{f=1} f' "$f" | grep -q 'probe: "true"'; then
        svc_ok=1
      fi
    fi
  done
  rm -rf "$split_dir"

  (( has_configmap == 1 && deploy_ok == 1 && svc_ok == 1 ))
}

candidate_ids=()
[[ -n "${KUSTOMIZE_BIN:-}" ]] && candidate_ids+=("kustomize_bin")
command -v kustomize >/dev/null 2>&1 && candidate_ids+=("kustomize")
command -v kubectl   >/dev/null 2>&1 && candidate_ids+=("kubectl")

if (( ${#candidate_ids[@]} == 0 )); then
  echo "ERROR: need either 'kustomize' or 'kubectl' on PATH (or KUSTOMIZE_BIN set)." >&2
  exit 2
fi

probe_err=""
renderer_id=""
for id in "${candidate_ids[@]}"; do
  if fixture_out="$(render_with "$id" "$fixture_dir" 2>"$stderr_file")"; then
    if assert_capability_output "$fixture_out"; then
      renderer_id="$id"
      break
    fi
    # Exited 0, but the rendered output doesn't actually show `components:` or
    # `includeSelectors` semantics honoured — not capable, keep probing.
    if [[ -z "$probe_err" ]]; then
      probe_err="$(label_for "$id") exited 0 on the fixture, but its output failed the capability assertions (missing the component's ConfigMap, and/or the injected label missing from the Deployment's or Service's selector)."
    fi
    continue
  fi
  [[ -z "$probe_err" ]] && probe_err="$(cat "$stderr_file")"
done

if [[ -z "$renderer_id" ]]; then
  echo "ERROR: no available renderer could build a minimal test overlay (using components: and labels:)." >&2
  echo >&2
  if [[ -n "$probe_err" ]]; then
    sed 's/^/    /' <<<"$probe_err" >&2
  fi
  if grep -qE 'unknown field "(components|labels)"' <<<"$probe_err"; then
    cat >&2 <<'EOF'

Every renderer found is too old for this repo: `components:` needs kustomize >= 3.7
and `labels:` needs >= 4.x. Fix it with one of:

  brew install kustomize                       # or your platform's package manager
  KUSTOMIZE_BIN=/path/to/kustomize tests/render-all.sh

Release binaries: https://github.com/kubernetes-sigs/kustomize/releases
EOF
  fi
  exit 2
fi

echo "Renderer: $(label_for "$renderer_id")"
echo
# --- End renderer selection ---------------------------------------------------

pass=0
skip=0
fail=0

for overlay_dir in "${overlay_dirs[@]}"; do
  name="$(basename "$overlay_dir")"

  if render_with "$renderer_id" "$overlay_dir" >/dev/null 2>"$stderr_file"; then
    echo "PASS: $name"
    pass=$((pass + 1))
    continue
  fi

  build_err="$(cat "$stderr_file")"

  # Reclassify to SKIP only if kustomize's own error names a missing secret.yaml
  # AND the file is genuinely absent (not some unrelated error that happens to
  # mention the string). This is the legitimate, expected case of a gitignored
  # secret that hasn't been rendered yet (e.g. a fresh clone) — never a guess.
  if is_missing_secret_failure "$overlay_dir" "$build_err"; then
    dummy_secret="${overlay_dir}secret.yaml"
    # serverPass is deliberately EMPTY, matching the tracked overlays/plain/secret.yaml
    # template — never a junk placeholder value. The trap below removes this file on
    # exit, but if the script were killed hard (e.g. SIGKILL) before that ran, this
    # dummy would be left sitting in a REAL overlay directory. An empty serverPass
    # means that leaked file can never stand up a running server with a junk
    # credential: kustomize renders it fine either way, but odin refuses to start
    # the server on an empty password, same as the plain overlay's own template.
    cat > "$dummy_secret" <<'YAML'
apiVersion: v1
kind: Secret
metadata:
  name: valheim-secrets
type: Opaque
stringData:
  serverPass: ""
YAML

    if render_with "$renderer_id" "$overlay_dir" >/dev/null 2>"$stderr_file"; then
      echo "SKIP (secret not rendered): $name — run scripts/render-secret.sh $name"
      skip=$((skip + 1))
      rm -f "$dummy_secret"
      dummy_secret=""
      continue
    fi

    # The overlay is broken for reasons beyond the missing secret — genuine FAIL,
    # with the second build's error (the real one) printed instead of the first.
    second_err="$(cat "$stderr_file")"
    rm -f "$dummy_secret"
    dummy_secret=""
    echo "FAIL: $name (missing secret AND a broken build beyond that)"
    sed 's/^/    /' <<<"$second_err"
    fail=$((fail + 1))
    continue
  fi

  echo "FAIL: $name"
  sed 's/^/    /' <<<"$build_err"
  fail=$((fail + 1))
done

echo
echo "Summary: ${pass} passed, ${skip} skipped, ${fail} failed"

if (( fail > 0 )); then
  exit 1
fi
