#!/usr/bin/env bash
# Render every kustomize overlay under kustomize/overlays/ and fail loudly if any
# genuinely fails to build. This is the cross-overlay counterpart to the one-off
# `kubectl kustomize kustomize/overlays/<one>` checks that were previously the only
# verification this repo had — for an infra repo with no unit-test suite, "every
# overlay still renders" IS the test.
#
# Usage: tests/render-all.sh
#
# Overlays are discovered dynamically (never hardcoded): ad-hoc instance overlays
# generated by scripts/start-server.sh are gitignored and come and go, so a fixed
# list would silently stop covering them.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OVERLAYS_DIR="$ROOT/kustomize/overlays"

pass=0
skip=0
fail=0

shopt -s nullglob
for overlay_dir in "$OVERLAYS_DIR"/*/; do
  name="$(basename "$overlay_dir")"
  kustomization="${overlay_dir}kustomization.yaml"

  # An overlay whose kustomization.yaml lists a gitignored secret.yaml in its
  # `resources:` but hasn't had one rendered yet (e.g. a fresh clone) is EXPECTED
  # to fail a kustomize build. Detect that specific, legitimate case up front and
  # report it as SKIP rather than FAIL, so a fresh clone never shows a false failure.
  if [[ -f "$kustomization" ]] \
      && grep -qE '^[[:space:]]*-[[:space:]]*secret\.yaml[[:space:]]*$' "$kustomization" \
      && [[ ! -f "${overlay_dir}secret.yaml" ]]; then
    echo "SKIP (secret not rendered): $name — run scripts/render-secret.sh $name"
    skip=$((skip + 1))
    continue
  fi

  if kubectl kustomize "$overlay_dir" >/dev/null; then
    echo "PASS: $name"
    pass=$((pass + 1))
  else
    echo "FAIL: $name"
    fail=$((fail + 1))
  fi
done

echo
echo "Summary: ${pass} passed, ${skip} skipped, ${fail} failed"

if (( fail > 0 )); then
  exit 1
fi
