#!/usr/bin/env bash
# Render an instance's valheim-secrets Secret from the environment, so a real
# password never lives in Git.
#
# Usage: render-secret.sh [overlay]           # default overlay: valheim7
#
# Reads $VALHEIM_SERVER_PASSWORD and writes kustomize/overlays/<overlay>/secret.yaml
# (gitignored). Deliberately contains NO kubectl call: it only writes a manifest, so
# it stays inert, is safe to run anywhere, and does not trip agent k8s guards that
# intercept scripts containing raw kubectl. Apply the overlay separately.
#
# In the GDD workspace the variable comes from yggdrasil's root .env, which `ws`
# loads before dispatching any subcommand:
#   ws exec kubicvalheim bash scripts/render-secret.sh
# Standalone, just export it yourself first.
set -euo pipefail

OVERLAY="${1:-valheim7}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_DIR="$ROOT/kustomize/overlays/$OVERLAY"

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "ERROR: overlay '$OVERLAY' not found at kustomize/overlays/$OVERLAY" >&2
  exit 1
fi

if [[ -z "${VALHEIM_SERVER_PASSWORD:-}" ]]; then
  echo "ERROR: VALHEIM_SERVER_PASSWORD is not set." >&2
  echo "  In the GDD workspace: add it to yggdrasil's root .env, then run this via" >&2
  echo "    ws exec kubicvalheim bash scripts/render-secret.sh $OVERLAY" >&2
  echo "  Standalone: export VALHEIM_SERVER_PASSWORD=... first." >&2
  exit 1
fi

# Valheim refuses to start on a password shorter than 5 characters.
if (( ${#VALHEIM_SERVER_PASSWORD} < 5 )); then
  echo "ERROR: VALHEIM_SERVER_PASSWORD must be at least 5 characters." >&2
  exit 1
fi

# Valheim also rejects a password that appears inside the server name, which would
# otherwise fail at runtime with a confusing error. Check it here instead.
SERVER_NAME="$(sed -n 's/^[[:space:]]*value:[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
  "$TARGET_DIR/instance-patch.yaml" | head -1)"
if [[ -n "$SERVER_NAME" && "$SERVER_NAME" == *"$VALHEIM_SERVER_PASSWORD"* ]]; then
  echo "ERROR: password must not be a substring of the server name ('$SERVER_NAME')." >&2
  exit 1
fi

# Quote defensively: a password may contain YAML-significant characters. Single-quoted
# YAML scalars escape an embedded single quote by doubling it.
ESCAPED="${VALHEIM_SERVER_PASSWORD//\'/\'\'}"

cat > "$TARGET_DIR/secret.yaml" <<YAML
# GENERATED by scripts/render-secret.sh from \$VALHEIM_SERVER_PASSWORD — do not commit,
# do not hand-edit. This path is gitignored; regenerate it instead.
apiVersion: v1
kind: Secret
metadata:
  name: valheim-secrets
type: Opaque
stringData:
  serverPass: '${ESCAPED}'
YAML

chmod 600 "$TARGET_DIR/secret.yaml"
echo "Rendered kustomize/overlays/$OVERLAY/secret.yaml from \$VALHEIM_SERVER_PASSWORD (mode 600, gitignored)."
