#!/usr/bin/env bash
# Render an instance's valheim-secrets Secret from the environment, so a real
# password never lives in Git.
#
# Usage: render-secret.sh [overlay]           # default overlay: valheim7
#
# Reads $VALHEIM_SERVER_PASSWORD and writes kustomize/overlays/<overlay>/secret.yaml
# (gitignored). Deliberately contains NO kubectl call: it only writes a manifest, so
# it stays inert, is safe to run anywhere, and does not trip agent k8s guards that
# intercept scripts containing raw kubectl. Apply the overlay separately.
#
# In the GDD workspace the variable comes from yggdrasil's root .env, which `ws`
# loads before dispatching any subcommand:
#   ws exec kubicvalheim bash scripts/render-secret.sh
# Standalone, just export it yourself first.
set -euo pipefail

OVERLAY="${1:-valheim7}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET_DIR="$ROOT/kustomize/overlays/$OVERLAY"

if [[ ! -d "$TARGET_DIR" ]]; then
  echo "ERROR: overlay '$OVERLAY' not found at kustomize/overlays/$OVERLAY" >&2
  exit 1
fi

# Refuse to write a real password anywhere git would track it. Only the overlay
# directory existing was checked above — .gitignore re-includes curated overlays
# like `plain/` wholesale and excludes just `valheim7/secret.yaml` by name, so an
# overlay that LOOKS gitignored (its directory is) can still have a TRACKED
# secret.yaml inside it. Writing there would put a live password straight into
# git. Fail closed: if git is unavailable, this isn't a repo, or check-ignore
# can't confirm the path is ignored, refuse rather than risk it — a false
# refusal costs a retry, a committed password does not undo.
if ! command -v git >/dev/null 2>&1; then
  echo "ERROR: git is not available, so this script cannot confirm '$TARGET_DIR/secret.yaml' is gitignored." >&2
  echo "  Refusing to write a real password where it might be tracked. Install git or write the secret manually." >&2
  exit 1
fi

if ! git -C "$ROOT" check-ignore -q "$TARGET_DIR/secret.yaml"; then
  echo "ERROR: '$TARGET_DIR/secret.yaml' is NOT gitignored (or '$ROOT' is not a git repo)." >&2
  echo "  Writing the real password there would put a live credential in git." >&2
  echo "  Use an instance overlay instead (e.g. one generated by scripts/start-server.sh, or 'valheim7')," >&2
  echo "  whose secret.yaml IS gitignored." >&2
  exit 1
fi

if [[ -z "${VALHEIM_SERVER_PASSWORD:-}" ]]; then
  echo "ERROR: VALHEIM_SERVER_PASSWORD is not set." >&2
  echo "  In the GDD workspace: add it to yggdrasil's root .env, then run this via" >&2
  echo "    ws exec kubicvalheim bash scripts/render-secret.sh $OVERLAY" >&2
  echo "  Standalone: export VALHEIM_SERVER_PASSWORD=... first." >&2
  exit 1
fi

# Valheim refuses to start on a password shorter than 5 characters.
if (( ${#VALHEIM_SERVER_PASSWORD} < 5 )); then
  echo "ERROR: VALHEIM_SERVER_PASSWORD must be at least 5 characters." >&2
  exit 1
fi

# Valheim also rejects a password that appears AS A SUBSTRING of the server name
# (or the world name) — e.g. name "Shattered Vikings" with password "vikings"
# refuses to start. That would otherwise fail at runtime with a confusing error,
# so it is checked here instead. instance-patch.yaml lists NAME before WORLD (the
# order scripts/start-server.sh always generates), so the first "value:" line is
# the server name and the second is the world name.
#
# Valheim's own check is case-INsensitive, so this one must be too — "Shattered
# Vikings" / "vikings" (the docstring example above) differ only in case, and a
# case-sensitive comparison here would wave it straight through to a server that
# refuses to start. Lowercase both operands into locals before comparing, rather
# than a scoped `nocasematch`, so nothing here depends on shell option state.
#
# ${VAR,,} is a Bash 4+ feature and macOS ships Bash 3.2 at /bin/bash, so it is a
# syntax error there (same reason scripts/start-server.sh avoids ${NAME^}).
# `tr '[:upper:]' '[:lower:]'` in a command substitution is the 3.2-compatible
# equivalent — do not "modernise" this back to ${,,}.
SERVER_NAME="$(sed -n 's/^[[:space:]]*value:[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
  "$TARGET_DIR/instance-patch.yaml" | head -1)"
SERVER_NAME_LC="$(printf '%s' "$SERVER_NAME" | tr '[:upper:]' '[:lower:]')"
PASSWORD_LC="$(printf '%s' "$VALHEIM_SERVER_PASSWORD" | tr '[:upper:]' '[:lower:]')"
if [[ -n "$SERVER_NAME" && "$SERVER_NAME_LC" == *"$PASSWORD_LC"* ]]; then
  echo "ERROR: password must not be a substring of the server name ('$SERVER_NAME'), case-insensitive." >&2
  exit 1
fi

WORLD_NAME="$(sed -n 's/^[[:space:]]*value:[[:space:]]*"\(.*\)"[[:space:]]*$/\1/p' \
  "$TARGET_DIR/instance-patch.yaml" | sed -n '2p')"
WORLD_NAME_LC="$(printf '%s' "$WORLD_NAME" | tr '[:upper:]' '[:lower:]')"
if [[ -n "$WORLD_NAME" && "$WORLD_NAME_LC" == *"$PASSWORD_LC"* ]]; then
  echo "ERROR: password must not be a substring of the world name ('$WORLD_NAME'), case-insensitive." >&2
  exit 1
fi

# Quote defensively: a password may contain YAML-significant characters. Single-quoted
# YAML scalars escape an embedded single quote by doubling it.
ESCAPED="${VALHEIM_SERVER_PASSWORD//\'/\'\'}"

# Never let the caller's umask leave the password briefly world- or group-readable.
# Under a common 022 umask, `cat >` would create the file mode 644 and it would stay
# that way from the first write until the chmod below — and would stay that way
# permanently if the script were interrupted in between. Tighten the umask before
# the write so the file is born 0600, then restore it immediately after.
#
# Write through a TEMP FILE in the same directory rather than redirecting straight
# into secret.yaml, then rename it over the target atomically. Redirecting directly
# has two problems this avoids: if secret.yaml already exists (e.g. a previous
# render at a looser mode, or one created before this script ever set a mode),
# `cat >` truncates its contents in place while leaving its EXISTING mode
# untouched until the chmod below — so an old 0644 file stays 0644 (world/group
# readable) for the whole write, and if the script is interrupted mid-write it is
# left there permanently, holding a partially-written credential at a loose mode.
# Writing to a freshly-created temp file (born 0600 under the tightened umask,
# never pre-existing, never loosely-permissioned) and `mv`-ing it over the target
# means the target path is never observed in a partially-written state: `mv`
# within the same directory (same filesystem) is atomic, so a concurrent read of
# secret.yaml always sees either the complete old file or the complete new one.
OLD_UMASK="$(umask)"
umask 077
TMP_FILE="$(mktemp "$TARGET_DIR/.secret.yaml.XXXXXX")"
# Clean up the temp file if anything below fails before the mv (e.g. a full disk
# mid-write); a no-op once the mv has already moved it into place.
trap 'rm -f "$TMP_FILE"' EXIT

cat > "$TMP_FILE" <<YAML
# GENERATED by scripts/render-secret.sh from \$VALHEIM_SERVER_PASSWORD — do not commit,
# do not hand-edit. This path is gitignored; regenerate it instead.
apiVersion: v1
kind: Secret
metadata:
  name: valheim-secrets
type: Opaque
stringData:
  serverPass: '${ESCAPED}'
YAML

# Belt-and-braces: restate the intended final mode even though the umask above
# already created the file that way.
chmod 600 "$TMP_FILE"
mv "$TMP_FILE" "$TARGET_DIR/secret.yaml"
umask "$OLD_UMASK"
echo "Rendered kustomize/overlays/$OVERLAY/secret.yaml from \$VALHEIM_SERVER_PASSWORD (mode 600, gitignored)."
